name: CI/CD for Recipes App

on: [push]

jobs:
  check-changes:
    # Checks if application code changed (in recipes-rs directory)
    runs-on: ubuntu-latest
    outputs:
      recipes_changed: 'true' # ${{ steps.filter.outputs.recipes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for changes in recipes-rs/
        id: filter
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^recipes-rs/'; then
            echo "recipes=true" >> $GITHUB_OUTPUT
          else
            echo "recipes=false" >> $GITHUB_OUTPUT
          fi

  build-and-push:
    # Builds a new version of Docker image if the app changed
    needs: check-changes
    if: needs.check-changes.outputs.recipes_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        working-directory: recipes-rs
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/recipes-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/recipes-app:latest

  cdk-deploy:
    # Run `cdk deploy`
    needs: [check-changes, build-and-push]
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install CDK and dependencies
        run: |
          pip install -r requirements.txt
          pip install aws-cdk-lib constructs

      - name: Run CDK deploy
        run: cdk deploy --require-approval never